CREATE TABLE IF NOT EXISTS t_device_locations (
  ID UUID PRIMARY key,
  DEVICE_ID UUID DEFAULT NULL,
  EMPLOYEE_ID UUID DEFAULT NULL,
  DATE_TIME TIMESTAMP(6) DEFAULT NULL,
  LATITUDE DOUBLE PRECISION DEFAULT NULL,
  LONGITUDE DOUBLE PRECISION DEFAULT NULL,
  ALTITUDE DOUBLE PRECISION DEFAULT NULL
);
